name: CI
on:
  push:

jobs:
  integrity:
    runs-on: ubuntu-latest
    name: Integrity Checks
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun i

      - name: Tests
        run: bun run test

      - name: Build Check
        run: bun run build
